### ISSUE TITLE
High memory usage in spreadsheet service

### ISSUE THREAD

**Issue by otherpirate** [googleworkspace/python-samples#169]
## Expected Behavior
Consume a reasonable memory size

## Actual Behavior
A simple instance of spreadSheet is consuming 84mb (84844795bytes)

## Steps to Reproduce the Problem
1. Declare a deep `get_size`, [example](https://gist.github.com/bosswissam/a369b7a31d9dcab46b4a034be7d263b2#file-pysize-py)
2. Python code
```
from googleapiclient.discovery import build
from google.oauth2.service_account import Credentials

credential = Credentials.from_service_account_file("./credential.json", scopes=['https://www.googleapis.com/auth/spreadsheets'])
get_size(credential)
### 3325

service = build('sheets', 'v4', credentials=credential)
get_size(service) # Note, this instance size will change in last line
### 1665250

spread = service.spreadsheets()
get_size(spread)
### 84844795

get_size(service) # Service size was updated
### 84843062
```

## Specifications

- Python version (`python --version`): Python 2.7.18
- OS (Mac/Linux/Windows): Fedora 32
- Lib version:
```
google-api-core==1.17.0
google-api-python-client==1.8.2
google-auth==1.14.1
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
googleapis-common-protos==1.51.0
```

**Comment by sqrrrl** [comment]
For issues with the python client, pleae report them at https://github.com/googleapis/google-api-python-client

**Comment by otherpirate** [comment]
Thanks @sqrrrl the repository has a similar issue
https://github.com/googleapis/google-api-python-client/issues/535
