### ISSUE TITLE
`Precondition check failed` error using Gmail (GSuite) account

### ISSUE THREAD

**Issue by risoms** [googleworkspace/python-samples#173]
## Expected Behavior
Using the example in: https://developers.google.com/gmail/api/quickstart/python: ` the code will attempt to open a new window or tab in your default browser. The sample will proceed automatically, and you may close the window/tab.`

## Actual Behavior
I'm returned the following error:
```
<HttpError 400 when requesting https://www.googleapis.com/gmail/v1/users//messages/send?alt=json returned "Precondition check failed.">
```

## Steps to Reproduce the Problem
1. Use Python Quickstart example for gmail
1.
1.

## Specifications
- Python version (`python --version`)
3.7
- OS (Mac/Linux/Windows)
Linux 2.6.32-954.3.5.lve1.4.77.el6

**Comment by sqrrrl** [comment]
Doesn't appear to be the quickstart (it doesn't call the method shown) so can't really help without additional details. Suggest asking for help on stackoverflow as the issue tracker here is primarily for reporting issues with the samples themselves, not general questions about the APIs.
