### ISSUE TITLE
How to get response code when service.events().list

### ISSUE THREAD

**Issue by techmodule** [googleworkspace/python-samples#176]
## I build one booking website using the Google Calendar API, i have one autoload.py will load events every 10 mins, everything oke if i have permission to acces calendarId, but If i dont have permission calendarId, my python file autoload.py stop run. So i need to know the way to get respose status_code for this function.

`events_result = service.events().list(calendarId=calendarId,
                                          timeMax=now,
                                          alwaysIncludeEmail=True,
                                          maxResults=100, singleEvents=True,
                                          orderBy='startTime').execute()`

## I want to know how to get respose status_code

1. If i have permission to acces calendarId, everything is ok.
2. If i dont have permission calendarId, my python stop running.
`  File "/Users/nguyenngoclinh/.conda/envs/1z_vietnam/lib/python3.7/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/pia9kapki9l4r9uejgf7r3leo4%40group.calendar.google.com/events?timeMax=2020-08-19T05%3A38%3A17.101875Z&alwaysIncludeEmail=true&maxResults=100&singleEvents=true&orderBy=startTime&alt=json returned "Not Found">`
So the way to get response status_code
## Specifications

- Python version (`python --version`)
- OS (Mac/Linux/Windows)

**Comment by sqrrrl** [comment]
See https://stackoverflow.com/questions/23945784/how-to-manage-google-api-errors-in-python
