### ISSUE TITLE
list of more than 1000 records download from Google Drive API in python

### ISSUE THREAD

**Issue by prashantenprocon** [googleworkspace/python-samples#177]
I have huge amount of html files in google drive, but only download 1000 html file. so please suggest me for the nextpageToken what should I do.

**Comment by sqrrrl** [comment]
For general help w/APIs, please use stackoverflow.com

There are some existing Q&As covering this topic, such as https://stackoverflow.com/questions/42980094/how-to-loop-over-nextpagetoken-using-googledrives-python-quickstart
