### ISSUE TITLE
Running Sample: Problem with authorising the quickstart application

### ISSUE THREAD

**Issue by CodingAlbert** [googleworkspace/python-samples#179]
## Expected Behavior

1. Upon opening the URL in order to authorize the application:
`Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=758636191562-f91q4r127599gmocnuhj1174emnhts2p.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A36699%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocuments.readonly&state=IgWTlqLngvyyKOVwFZKmwD7Hu0cjqU&access_type=offline
`

2. I choose the google account I want to authorise it under in my browser.

3. I pass the 'This app isn't verified' warning by choosing 'advanced' and 'Go to Quickstart (unsafe)'

4. I grant Quickstart permission to:

'View your Google Docs documents'

by pressing 'Allow'

5. I Confirm my choices:

'You are allowing Quickstart to:
View your Google Docs documents'

by pressing another 'Allow' 

6. I expect the authorisation to complete 

## Actual Behavior

In step 6. my browser is redirected to:
http://localhost:36699/?state=IgWTlqLngvyyKOVwFZKmwD7Hu0cjqU&code=4/5AH68eJGbKOCELt3-VmALywnAP3_S9SzmJAvi0fgtfcgkjURLLtchfLtS84Lbi7cLYndZxjc8aFFNwC_VqPwrOg&scope=https://www.googleapis.com/auth/documents.readonly

and I receive a browser error:

This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

## Steps to Reproduce the Problem

1. Start a remote server with Ubuntu
2. Connect to it via a single port by ssh
3. Install python3
4. Run: pip3 install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
5. Make sample script according to https://developers.google.com/docs/api/quickstart/python
6. run the sample script from the command line

## Specifications

- Python 3.8.5
- Linux ubuntu 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sqrrrl** [comment]
The sample isn't intended to be run on a remote server unless you're using a remote desktop solution. Localhost is relative -- in this case, you're running the sample, which temporarily acts like a server, remotely by the browser locally. Since there is no server running locally you'll get that error.

Either run the sample locally or use something like chrome remote desktop when accessing your remote server.
