### ISSUE TITLE
Issue with authorising

### ISSUE THREAD

**Issue by generationzcode** [googleworkspace/python-samples#192]
## Expected Behavior
I expected the auth window to close and go back to my colab workbook
## Actual Behavior
After I clicked on "allow", the window loaded to localhost, which was not recognised by chrome and said that the website took too long to load. Did this 5 to 6 times

## Steps to Reproduce the Problem

1. Start a quickstart project
2.Write some code on colabratory
3.try and run the code and authorise the application

## Specifications

- Python version (`python --version`)
- colabratory

**Comment by sqrrrl** [comment]
The quickstart is not intended to be run directly in colab. It's meant to be run locally. The auth part of the quickstart would need to be rewritten to work in colab.

You can try and change`run_local_server` to `run_console` to prevent it from starting up a server on localhost (which in colab case would be inaccessible) and have it expect to get the auth code via user input. I'm not super familiar with colab's environment and not sure if that would have other issues, but I'd start there.
