### ISSUE TITLE
Can't import InstalledAppFlow

### ISSUE THREAD

**Issue by luudanmatcuoi-vn** [googleworkspace/python-samples#197]
## Actual Behavior

![image](https://user-images.githubusercontent.com/44934736/112715969-3075a180-8f16-11eb-8d63-484c0151174b.png)

## Steps to Reproduce the Problem

1. Run quick start example and got this error
2. reinstall everything and still got this error

## Specifications

- Python version (3.8.1)
- OS (Windows)

**Comment by YoelMonsalve** [comment]
It's strange. Sometimes it does not work properly unless than you create a [virtualenv](https://docs.python.org/3/library/venv.html) and run the app from there.

But .... string containing **"null bytes"** (???) How is it possible?
