### ISSUE TITLE
Issue with history.list() api from gmail api sdk python

### ISSUE THREAD

**Issue by aaaguirrep** [googleworkspace/python-samples#200]
Hi, I am using GMAIL API to automate an internal process, I need to read an email address. I am using the next guide: https://developers.google.com/gmail/api/guides/push, I receive the notification in my webhook after a new mail is received, I am using the historyid with history.list() but it doesnt show the history[] in the response. It just shows historyId.

I received the next data in the webhook:
{'emailAddress': 'xxxxx@xxxxx.com', 'historyId': 1710}

I use the historyId and I trigger the next api
history_email = results.users().history().list(userId=user_email, startHistoryId = 'historyId').execute()

It responses with the next data:
{'historyId': '1710'}

So, I am not seeing the history[]

What are I doing wrong?

Thanks in advance.

Regards,
Arsenio

**Comment by sqrrrl** [comment]
For general help/how-to questions, please use StackOverflow. This issue tracker is only for the samples contained here.
