### ISSUE TITLE
Get status code response from sdk

### ISSUE THREAD

**Issue by treydin6** [googleworkspace/python-samples#207]
## Expected Behavior
I want to create a new user and get a response status code.
The Google admin sdk docs say I should receive a 200 status code on success, But I don't know how to get that code.

## Actual Behavior
I just get the newly created user object which is no good to me. 

## Steps to Reproduce the Problem
I can sucessfully create a user, So everything works fine. I just want status codes for error handling

new_user = {....}
result = service.users().insert(body=new_user).execute()

does the result have of some sort of status code with it that I can capture?

**Comment by sqrrrl** [comment]
The client will throw an error for non-success status codes. For successful requests, it'll return the body of the response.

In the future, please use StackOverflow for general how-to questions. This issue tracker is intended only for the samples contained here.
