### ISSUE TITLE
error 404 Requested entity was not found.

### ISSUE THREAD

**Issue by CharleoY** [googleworkspace/python-samples#208]
## Expected Behavior
I want to update the content of script dynamically and create a deployment, finally execute it with python client by following code.
api.projects().updateContent(scriptId=scriptId,body=body).exexcute()
api.projects().deployments().create(scriptId=scriptId,body=body).execute()
api.scripts().run(scriptId=scriptId,body=body).execute()
## Actual Behavior
When execute `api.projects().updateContent(scriptId=scriptId,body=body).exexcute()`, it only update the HEAD branch(Version 0) of the script. 
Then if I create a deployment using `api.projects().deployments().create(scriptId=scriptId,body=body).execute()`, I have to define an versionNumber in body. If I use 0 then there will be an exception: Error 400 New deployments must have a non-zero version number. 
If I want to change the version using `api.projects().versions().create(scriptId=scriptId,body=body).execute()`, the generated snapshot will be read-only and can not execute.

The question is: since I have to update the script every time, how can I update the script, deploy, and execute with python client, instead to run it in the Apps Script editor?

## Steps to Reproduce the Problem

1. Add the following code after line 70 of quickstart.py and Assign the GCP project number to the script project.

2. try:
            deployBody = {"description": "Publish", "versionNumber": 1}
            response = service.projects().deployments().create(scriptId=response['scriptId'],body = deployBody).execute()
        except Exception as e:
            print(e)
        try:
            executeBody = {"function":"helloWorld","devMode": "true"}
            response = service.scripts().run(scriptId=response['scriptId'],body = deployBody).execute()
        except Exception as e:
            print(e)

3. Exceptions of "error 404 Requested entity was not found." will show up

## Specifications

- Python version (`python --version`) 3.7
- OS (Mac/Linux/Windows) ubuntu20.04

**Comment by sqrrrl** [comment]
For general help/how-to advice, please use StackOverflow. This issue tracker is only for issues with the samples contained here.
