### ISSUE TITLE
Merge Multiple Google Calendars Into One and list the events of all calender.

### ISSUE THREAD

**Issue by Rajendraladkat1919** [googleworkspace/python-samples#210]
## Expected Behavior
Suppose I have more than two email account. I want to list calender events of each account together and from that list I want to decide which events from calender is important. when I follow tutorial listed below 
`https://developers.google.com/calendar/api/quickstart/python ` I can only able to list events from the single account calender only for which I have given access. Also I have shared other account calender with first one but only auth is created for single account only showing the events from single .

## Actual Behavior

When we shared the one account calender with second account and when we generate auth key for the second account then python client can list the google calender events of second account as well as first account.

## Steps to Reproduce the Problem

1.  Follow all the steps from this tutorial https://developers.google.com/calendar/api/quickstart/python
2. create events in another gemail account and share with the first account calender.
3. First account accept this events from the first account.
4. run the quicksetup script  and check wheather we are able to see google calender events from the both email account.

## Specifications

- Python version : Python 3.9.5
- OS (Mac/Linux/Windows): Mac

**Comment by sqrrrl** [comment]
Please use StackOverflow for general how-to questions about the APis.

From the description, it's not at all clear if there's an actual issue here. The quickstart just shows the next 10 events on the users primary calendar. You'll have to modify the code if you'd like to read events from other calendars the user might have. If there's a particular bug with the quickstart, let me know, otherwise this appears to be working as intended.

**Comment by Rajendraladkat1919** [comment]
@sqrrrl  Are you sure modifying the code will shows calender events of multiple account's of same user? The actual requirement is when one user have multiple google account then when I write the utlity using the quick start guide I can only see the events of one account not of the all account. Suppose we create auth for 5 gmail account and try to get events for these 5 gmail account's it will shows events for the account using which we logged in. I am not sure this is bug or feature requirement :)

**Comment by sqrrrl** [comment]
Maybe misread original comments, but thought you were trying to use shared calendars, not completely separate accounts. With shared calendars, it should be possible to modify the quickstart to fetch from multiple calendars using a single user's credentials.

If you're trying to aggregate multiple accounts without relying on calendar sharing, then you'll need to authorize multiple times and manage storing those credentials.
