### ISSUE TITLE
quickstart.py - FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

### ISSUE THREAD

**Issue by maxloopinmok** [googleworkspace/python-samples#216]
I'm running pip and python from the Anaconda Prompt on my Windows 10 PC.  I've 2 Google Drives running on virtual drives G and H.  I've done Step 1 and 2 from https://developers.google.com/apps-script/api/quickstart/python.  

When I got to Step 3, I got this error:

```
(base) C:\Users\Max\Downloads>python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 81, in <module>
    main()
  File "quickstart.py", line 45, in main
    'credentials.json', SCOPES)
  File "C:\Users\Max\anaconda3\lib\site-packages\google_auth_oauthlib\flow.py", line 201, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'
```

In the quickstart.py file, I've tried changing this:

`flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)`

To this:

`flow = InstalledAppFlow.from_client_secrets_file('C:\Users\Max\Downloads\credentials.json', SCOPES)`

And to this:

`flow = InstalledAppFlow.from_client_secrets_file('G:\My Drive\Google Sheets\credentials.json', SCOPES)`

I've a copy of credentials.json at both locations, but both didn't work.  I've tried setting the Windows Path variable to include G:\My Drive\Google Sheets, but that didn't work either.  I also did this from the command prompt based on these instructions: https://cloud.google.com/docs/authentication/getting-started#windows.  

`set GOOGLE_APPLICATION_CREDENTIALS="G:\My Drive\Google Sheets\credentials.json"`

But that didn't work too.  

I then tried the same steps with new credentials.json and quickstart.py based on instructions from: https://developers.google.com/sheets/api/quickstart/python.  

I got a similar error:

```
(base) G:\My Drive\Google Sheets>python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 54, in <module>
    main()
  File "quickstart.py", line 31, in main
    'credentials.json', SCOPES)
  File "C:\Users\Max\anaconda3\lib\site-packages\google_auth_oauthlib\flow.py", line 201, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'
```

Does anyone know how to resolve this?  Is there a way to set the working directory?

_Originally posted by @maxloosmu in https://github.com/googleworkspace/python-samples/issues/134#issuecomment-950338118_

**Comment by aliasgarshaikh1904** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'api-key.json'
