### ISSUE TITLE
 Google form : token.json create but code will not use this token.json file 

### ISSUE THREAD

**Issue by kinshusharma0412** [googleworkspace/python-samples#303]
from __future__ import print_function

from apiclient import discovery
from httplib2 import Http
from oauth2client import client, file, tools

SCOPES = "https://www.googleapis.com/auth/drive"
DISCOVERY_DOC = "https://forms.googleapis.com/$discovery/rest?version=v1"

store = file.Storage('token.json')
creds = None
if not creds or creds.invalid:
    flow = client.flow_from_clientsecrets('client_secrets.json', SCOPES)
    creds = tools.run_flow(flow, store)

form_service = discovery.build('forms', 'v1', http=creds.authorize(
    Http()), discoveryServiceUrl=DISCOVERY_DOC, static_discovery=False)

form = {
    "info": {
        "title": "My new form",
    },
}

result = form_service.forms().create(body=form).execute()
print(result)

#Using this script I save token.json file successful 👍
#But when I run second time this script it is not using token.json file In-spite of this it go to authorization section 

#How can I use this token.json file so I run my script on heroku without authorization to my google drive every time

**Comment by sqrrrl** [comment]
For general help about APIs, please use StackOverflow. This issue tracker is for issues related to the sample code contained here.

To answer the question though, `tools.run_flow` doesn't check if credentials exist, it just blindly starts the auth flow. You'll need to do that yourself via `file.locked_get()`
