### ISSUE TITLE
Gmail Api Not working on Cloud

### ISSUE THREAD

**Issue by dhwaj1902** [googleworkspace/python-samples#326]
# Summary
I am using Gmail API to send emails to users. It was working fine at my localhost, but when I pushed my code to the cloud(in my case digital ocean Linux server), it stops working and starts to show the following error:
``[Errno 98] Address already in use``
Also, I have checked that the port which I have assigned to this is not opened by any other application/

## Configurations
Application Type: Desktop Application
Using Apache2 on sever

## Specifications

- Python version (`Python 3.6.9`)
- OS (Linux)

**Comment by sqrrrl** [comment]
This issue tracker is only for issues with the samples here. For help with APIs in general, see https://developers.google.com/gmail/api/support
