### ISSUE TITLE
Typo in the code: key specifying the name of the folder

### ISSUE THREAD

**Issue by hanlee55** [googleworkspace/python-samples#339]
https://github.com/googleworkspace/python-samples/blob/bc61a48f13f1e29d4ded0c66bc7e244b0417b928/drive/snippets/drive-v3/file_snippet/create_folder.py#L38-L41

I think the string in the key specifying the folder name is 'name', not 'title'

``` python
file_metadata = {
    'name': 'Invoices',
    'mimeType': 'application/vnd.google-apps.folder'
}
```

**Comment by edel-david** [comment]
This typo is critical in my opinion.
I had to search for hours to find why the Folder was not named correctly
Pls change

Also, this comment seams wrong:

https://github.com/googleworkspace/python-samples/blob/bc61a48f13f1e29d4ded0c66bc7e244b0417b928/drive/snippets/drive-v3/file_snippet/create_folder.py#L35-L37

Arent we creating an drive api client here?

edit: there is a pull request to change the comment, but not the dict key

**Comment by hanlee55** [comment]
> This typo is critical in my opinion.
> I had to search for hours to find why the Folder was not named correctly
> Pls change

Thank you for reviewing the issue.

Yes, I also found a typo (gmail->drive) in the comment, but I didn't raise the issue because the pull request has already been submitted.

**Comment by edel-david** [comment]
im not sure but i think the only pull request i found was for a different file with the same typo.
👍
