### ISSUE TITLE
`drive` `v3` files create sample code - erroneous parameter `fields`

### ISSUE THREAD

**Issue by parthea** [googleworkspace/python-samples#367]
https://github.com/googleworkspace/python-samples/blob/44f307f5548d1c4d225746264a7bc4568e9c735e/drive/snippets/drive-v3/file_snippet/upload_basic.py#L44-L45

[This sample](https://github.com/googleworkspace/python-samples/blob/main/drive/snippets/drive-v3/file_snippet/upload_basic.py) uses the `fields` argument but I don't see this in the [API documentation](https://developers.google.com/drive/api/v3/reference/files/create). It seems to be a bug in the sample code.

**Comment by sqrrrl** [comment]
See https://developers.google.com/drive/api/guides/query-parameters and https://cloud.google.com/apis/docs/system-parameters
