### ISSUE TITLE
Prompt for authorization every single time

### ISSUE THREAD

**Issue by saqibfida** [googleworkspace/python-samples#370]
# Summary

TODO...

## Expected Behavior
It should prompt for authorization only for the first time.
TODO...

## Actual Behavior
prompt for authorization every time I run the code.
TODo...

## Steps to Reproduce the Problem

1.I used the sample code with my credentials.json file, as per google form documentation it should prompt for authorization only for the first time and store the authorization information locally but when I run the code it goes for authorization every single time.

## Specifications

- Python version (`3.9.7`)
- OS (Windows)

**Comment by presentformyfriends** [comment]
Coming up on a year and no reply. Is anyone even reading these issues?

**Comment by jpoehnelt** [comment]
Whether it prompts or not is entirely dependent on the code. Many of the samples are created such that they always prompt so that the appropriate scopes are available.
