### ISSUE TITLE
google drive OAuth does not work

### ISSUE THREAD

**Issue by dfyzicka** [googleworkspace/python-samples#814]
when i use python-samles/drive/quickstart i get such message after entering credentials
"failed to login
JavaScript support is disabled or missing in the browser you are using"
what am I doing wrong?
i use this on my vps with ubuntu 23 cli only

**Comment by presentformyfriends** [comment]
@sqrrrl Update?

**Comment by jpoehnelt** [comment]
This seems unrelated to the Google Drive API or OAuth.
